/*++

Copyright (c) 2005-2012 Intel Corporation. All rights reserved
This software and associated documentation (if any) is furnished
under a license and may only be used or copied in accordance
with the terms of the license. Except as permitted by such
license, no part of this software or documentation may be
reproduced, stored in a retrieval system, or transmitted in any
form or by any means without the express written consent of
Intel Corporation.

Module Name:

    File name:    MmrcProjectDataGenerated.h
    Date:             12/11/2013
    Input File: ValleyviewA0_04_17_2013_VLV_B0_MRC_0p92.mdb
    Revision:     v1.00-ww08

Abstract:

    THIS FILE IS AUTO-GENERATED BY THE MMRC TOOL. DO NOT CHANGE THIS CODE.

    If edits are needed in this file, they must be done via the MMRC tool.

    If there is additional project-specific data required by the MMRC, it
    can be placed in MmrcProjectData.h, which is used for non-tool-generated
    data.

    This file contains data structures for a particular piece of silicon.
    These structures are fed to MmrcLibraries.c, which use them to initialize
    memory.

--*/

#ifndef _MMRCPROJECTDATAGENERATED_H_
#define _MMRCPROJECTDATAGENERATED_H_

#include "MMRCProjectRegisters.h"
#include "MMRCLibraries.h"

//
// CMRB Condition Macros
// The macros for decoding the conditional statements on PFCT values.    
// Example when xPxxxx is applied, the conditional statements for this assignment will all be P(x)
//                            xxFCxx is applied, the conditional statements for this assignment will all be FC(x,y)
//
#define T(t)                                        CONV1( (t) )
#define C(c)                                        CONV1( (c) )
#define CT(c,t)                                 CONV2(( (c<<(NUM_TYPE)) + (t) ))
#define F(f)                                        CONV1( (f) )
#define FT(f,t)                                 CONV2(( (f<<(NUM_TYPE)) + (t) ))
#define FC(f,c)                                 CONV2(( (f<<(NUM_CONF)) + (c) ))
#define FCT(f,c,t)                            CONV3(( (f<<(NUM_CONF + NUM_TYPE)) + (c<<(NUM_TYPE)) + (t) ))
#define P(p)                                        CONV2( (p) )
#define PT(p,t)                                 CONV2(( (p<<(NUM_TYPE)) + (t) ))
#define PC(p,c)                                 CONV3(( (p<<(NUM_CONF)) + (c) ))
#define PCT(p,c,t)                            CONV3(( (p<<(NUM_CONF + NUM_TYPE)) + (c<<(NUM_TYPE)) + (t) ))
#define PF(p,f)                                 CONV2(( (p<<(NUM_FREQ)) + (f) ))
#define PFT(p,f,t)                            CONV3(( (p<<(NUM_FREQ + NUM_TYPE)) + (f<<(NUM_TYPE)) + (t) ))
#define PFC(p,f,c)                            CONV3(( (p<<(NUM_FREQ + NUM_CONF)) + (f<<(NUM_CONF)) + (c) ))
#define PFCT(p,f,c,t)                     CONV4(( (p<<(NUM_FREQ + NUM_CONF + NUM_TYPE)) + (f<<(NUM_CONF + NUM_TYPE)) + (c<<(NUM_TYPE)) + (t) ))

//
// Platform, Frequency, Configuration and Type Definitions
//
// Platform
//
#define PLAT_SV_DDR3L_ALPINE_VALLEY              0
#define PLAT_SV_DDR3L_ECC_ALPINE_VALLEY          1
#define PLAT_SV_LPDDR3_ALPINE_VALLEY             2
#define PLAT_BDV_DDR3L_SUMMER_VALLEY             3
#define PLAT_EV_DDR3L_BAY_TRAIL                  4
#define PLAT_EV_DDR3L_ECC_BAYLEY_BAY             5
#define PLAT_EV_LPDDR3_BAYLAKE                   6
#define PLAT_BDV_LPDDR3_SUMMER_VALLEY            7
#define PLAT_SIM                                 8
//
// Frequency
//
#define FREQ_800                                 0
#define FREQ_1066                                1
#define FREQ_1333                                2
#define FREQ_800_DDLL                            3
#define FREQ_800_DDLL_BYP_MPLL                   4
#define FREQ_1066_DDLL                           5
#define FREQ_1333_DDLL                           6
//
// Configuration
//
#define CONFIG_NCRCB                             0
#define CONFIG_NCRCC                             1
#define CONFIG_NCRCF                             2
#define CONFIG_NCRCA                             3
#define CONFIG_NCRCD                             4
#define CONFIG_NCRCE                             5
#define CONFIG_MBDOWN_1R                         6
#define CONFIG_MBDOWN_2R                         7
//
// Type
//
#define TYPE_DDR3L                               0
#define TYPE_DDR3L_ECC                           1
#define TYPE_LPDDR3                              2

#define MODULE_OFFSET 0x800   

extern CONST PHYINIT_LIST        HIP_rcvn_list[];
extern CONST PHYINIT_LIST        HIP_rdvref_list[];
extern CONST PHYINIT_LIST        HIP_rd_list[];
extern CONST PHYINIT_LIST        HIP_wr_list[];
extern CONST PHYINIT_LIST        HIP_wrlvlfine_list[];
extern CONST PHYINIT_LIST        HIP_wrlvlcoarse_list[];
extern CONST DIGITAL_DLL_LIST mmrcDigitalDLL[];
extern CONST UINT32 cpu_base_freq_mhz[];
extern CONST LP_TABLE        gRankToRankOffset[];
extern CONST LP_TABLE        gByteLaneOffsetWithinModule[];
extern STATUS MMRCSFRVolSel (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCPLLInit (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDRStaticInit2 (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDRStaticInitPerf (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDRStaticPwrClkGating (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDRStaticSim (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDLLInit (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCCompInit1 (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCCompInit2 (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCCompInitOVR (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCPeriodicCompInit (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCHMCInit (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCWrPointerInit (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCIOBUFACTInit (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCPreJedecInit (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDR3Reset (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDRStaticPowerGatingEnable (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDRStaticInitPerfEnable (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCWarmResetMPLLBypass (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCCompInit1_1CH (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCSFRVolSel1CH (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDRStaticInit1CH (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCPI2XDB_1CH (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCCompInit_LP31333 (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCDDRStaticInitPerfEnableLP31333 (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCCH0_X32 (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCCH1_X32 (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRC3LMB_COMP (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCRxPow (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS MMRCCPUODT (MMRC_DATA *ModMrcData, UINT8 Channel);
extern STATUS DynamicAssignment1 (MMRC_DATA *ModMrcData, UINT8 Channel, UINT8 Index, UINT32 *Value);

#define ___T________________________________________________________________________________________________________1___1 T(3)
#define ___T____________________________________________________________________________________________________1________ T(4)
#define _F__________________________________________________1___1___________1____________________________________________ F(25)
#define _F______________________________________________1_______________1________________________________________________ F(34)
#define _F__________________________________________1_______________1____________________________________________________ F(68)
#define _F_T________________________________________1___1___________1___1_______________________________________1________ FT(102,4)
#define _F_T________________________________________________1___1___________1___________________________________1________ FT(25,4)
#define _F_T________________________________________1___1___________1___1___________________________________________1___1 FT(102,3)
#define _F_T________________________________________________1___1___________1_______________________________________1___1 FT(25,3)
#define _F__________________________________________1___1___________1___1________________________________________________ F(102)
#define ___T________________________________________________________________________________________________________1____ T(2)
#define ___T____________________________________________________________________________________________________1_______1 T(5)
#define P_______1________________________________________________________________________________________________________ P(256)
#define PF_T____1_______________________________________1___1___1___1___1___1___________________________________1___1___1 PFT(256,63,7)
#define PF_T____________1_______________1___________________________________1___________________________________1________ PFT(68,1,4)
#define PF_T____________1_______________1_______________________________1_______________________________________1________ PFT(68,2,4)
#define PF_T____________1_______________1___________________________1___________________________________________1________ PFT(68,4,4)
#define PF_T____________1_______________1___________________1___1_______________________________________________1________ PFT(68,24,4)
#define PF_T____________1_______________1_______________1_______________________________________________________1________ PFT(68,32,4)
#define _F_T____________________________________________1_______________1_______________________________________1________ FT(34,4)
#define _F_T________________________________________________________1___________________________________________1________ FT(4,4)
#define _F_T____________________________________________1___1___1___1___1___1_______________________________________1___1 FT(63,3)
#define _F_T________________________________________________________1___1___1___________________________________1___1___1 FT(7,7)
#define _F_T________________________________________1___1___1___1_______________________________________________1_______1 FT(120,5)
#define _F__________________________________________________________1___1___1____________________________________________ F(7)
#define _F______________________________________________1___1___1________________________________________________________ F(56)
#define PF_T____1_______________________________________1___1___1___1___1___1_______________________________________1___1 PFT(256,63,3)
#define PF_T____________________1___1___________1_______________________1_______________________________________________1 PFT(25,2,1)
#define PF_T________________1_______________1___________________________1___________________________________________1____ PFT(34,2,2)
#define PF_T________1___1_______________1_______________1_______________________________________________________1________ PFT(196,32,4)
#define PF_T________1___1_______________1___________________1___1_______________________________________________1________ PFT(196,24,4)
#define PF_T____________________1___1___________1___________________________1___________________________________________1 PFT(25,1,1)
#define PF_T________________1_______________1_______________________________1_______________________________________1____ PFT(34,1,2)
#define PF_T____________________1___1___________1___________________1___________________________________________________1 PFT(25,4,1)
#define PF_T________________1_______________1_______________________1_______________________________________________1____ PFT(34,4,2)
#define PF_T____1_______________________________________1___1___1___1___1___1___________________________________1________ PFT(256,63,4)
#define PF_T________1___1_______________1_______________________________1___1___________________________________1________ PFT(196,3,4)
#define PF_T________1___1_______________1___________________________1___________________________________________1________ PFT(196,4,4)
#define PF_T____________________1___________________1___________________________________________________________________1 PFT(16,64,1)
#define PF_T____1_______________________________________1___1___1___1___1___1___________________________________1___1___1 PFT(256,63,7)
#define PF_T________1___1_______________1_______________________________1_______________________________________1________ PFT(196,2,4)
#define PF_T________1___1_______________1___________________________________1___________________________________1________ PFT(196,1,4)
#define PF_T________1___1_______________1_______________1___1___1___1___1___1___________________________________1________ PFT(196,63,4)
#define PF_T____________________1___1___________1___________________1___1_______________________________________________1 PFT(25,6,1)
#define PF_T________________1_______________1_______________________1___1___________________________________________1____ PFT(34,6,2)
#define PF_T____________________1___1___________1_______________________1_______________________________________________1 PFT(25,2,1)
#define PF_T________________1_______________1___________________________1___________________________________________1____ PFT(34,2,2)
#define PF_T____________________1___1___________1_______________________1___1___________________________________________1 PFT(25,3,1)
#define PF_T________________1_______________1___________________________1___1_______________________________________1____ PFT(34,3,2)
#define PF_T____________________1___________________1____________________________________________________________________ PFT(16,64,16)
#define _F_T________________________________________1___1___1___1___1___1___1___________________________________1___1___1 FT(127,7)
#define PF_T____________________1___1___________1___________________1_______1___________________________________________1 PFT(25,5,1)
#define PF_T________________1_______________1_______________________1_______1_______________________________________1____ PFT(34,5,2)
#define P___________1___1___1___1___1___1___1___1________________________________________________________________________ P(255)
#define _F_T________________________________________________________1___1___1_______________________________________1___1 FT(7,3)
#define _F_T________________________________________1_______________1___________________________________________1________ FT(68,4)
#define _F_T________________________________________1___1___1___1_______________________________________________________1 FT(120,1)
#define _F_T________________________________________1___1___1___1___1___1___1___________________________________1________ FT(127,4)
#define PF_T____________________________1___________1___1___1___1___1___1___1___________________________________1________ PFT(4,127,4)
#define PF_T________1___1_______________________________1___1___1_______1___1___________________________________1________ PFT(192,59,4)
#define PF_T________1___1_______________1___________1___1___1___1_______________________________________________1________ PFT(196,120,4)
#define P__T________1___1___1___1___1___1___1___1_______________________________________________________________1___1___1 PT(255,7)
#define P__T____1_______________________________________________________________________________________________1________ PT(256,4)
#define PF_T________1___1___1___1___1___1___1___1___1___1___1___1___1___1___1___________________________________1___1___1 PFT(255,127,7)
#define PF_T____1___________________________________1___1___1___1___1___1___1___________________________________1___1___1 PFT(256,127,7)
#define _F_T____________________________________________________________1___1___________________________________1_______1 FT(3,5)
#define _F_T____________________________________________________________1___1_______________________________________1____ FT(3,2)
#define _F_T________________________________________1___1___1___1___1___________________________________________1___1___1 FT(124,7)
#define PF_T____1_______________________________________________________1_______________________________________1________ PFT(256,2,4)
#define PF_T____1___________________________________________________1_______1___________________________________1________ PFT(256,5,4)
#define _F__________________________________________1___1___1___1________________________________________________________ F(120)
#define _F__________________________________________________1___1________________________________________________________ F(24)
#define _F______________________________________________1________________________________________________________________ F(32)
#define _F__________________________________________1____________________________________________________________________ F(64)
#define ___T____________________________________________________________________________________________________1___1___1 T(7)
#define P__T____1___________1___1___1_______1___1___________________________________________________________________1___1 PT(315,3)
#define P__T____1___1___1_______________1_______________________________________________________________________1________ PT(452,4)
#define P__T____1___________1___1___1_______1___1___________________________________________________________________1___1 PT(315,3)
#define P__T____1___1___1_______________1_______________________________________________________________________1________ PT(452,4)
#define _F_T____________________________________________1_______________1___________________________________________1___1 FT(34,3)
#define _F_T________________________________________1_______________1_______________________________________________1___1 FT(68,3)
#define _F_T________________________________________________________________1___________________________________1________ FT(1,4)
#define _F_T____________________________________________________________1_______________________________________1________ FT(2,4)
#define _F_T________________________________________1___1___1___1___1___________________________________________1_______1 FT(124,5)
#define _F_T________________________________________________________1___1___1_______________________________________1____ FT(7,2)
#define P__T________________1___1___1_______1___1___________________________________________________________________1___1 PT(59,3)
#define P__T________1___1_______________________________________________________________________________________1________ PT(192,4)
#define P__T____________________________1_______________________________________________________________________1________ PT(4,4)
#define ___T____________________________________________________________________________________________________________1 T(1)
#define _F_T________________________________________________1___1___________1___________________________________________1 FT(25,1)
#define _F_T____________________________________________1_______________1_______________________________________________1 FT(34,1)
#define _F_T________________________________________1_______________1___________________________________________________1 FT(68,1)


#endif //_MMRCPROJECTDATAGENERATED_H_
